// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ns.proto

#include "ns.pb.h"
#include "ns.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ns {

static const char* NetStatsService_method_names[] = {
  "/ns.NetStatsService/GetNetStats",
};

std::unique_ptr< NetStatsService::Stub> NetStatsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NetStatsService::Stub> stub(new NetStatsService::Stub(channel, options));
  return stub;
}

NetStatsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetNetStats_(NetStatsService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NetStatsService::Stub::GetNetStats(::grpc::ClientContext* context, const ::ns::Request& request, ::ns::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ns::Request, ::ns::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNetStats_, context, request, response);
}

void NetStatsService::Stub::async::GetNetStats(::grpc::ClientContext* context, const ::ns::Request* request, ::ns::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ns::Request, ::ns::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNetStats_, context, request, response, std::move(f));
}

void NetStatsService::Stub::async::GetNetStats(::grpc::ClientContext* context, const ::ns::Request* request, ::ns::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNetStats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ns::Response>* NetStatsService::Stub::PrepareAsyncGetNetStatsRaw(::grpc::ClientContext* context, const ::ns::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ns::Response, ::ns::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNetStats_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ns::Response>* NetStatsService::Stub::AsyncGetNetStatsRaw(::grpc::ClientContext* context, const ::ns::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNetStatsRaw(context, request, cq);
  result->StartCall();
  return result;
}

NetStatsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NetStatsService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NetStatsService::Service, ::ns::Request, ::ns::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NetStatsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ns::Request* req,
             ::ns::Response* resp) {
               return service->GetNetStats(ctx, req, resp);
             }, this)));
}

NetStatsService::Service::~Service() {
}

::grpc::Status NetStatsService::Service::GetNetStats(::grpc::ServerContext* context, const ::ns::Request* request, ::ns::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ns

