// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ns.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ns_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ns_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ns_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ns_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ns_2eproto;
namespace ns {
class ARPStats;
struct ARPStatsDefaultTypeInternal;
extern ARPStatsDefaultTypeInternal _ARPStats_default_instance_;
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class Response_ArpStatsEntry_DoNotUse;
struct Response_ArpStatsEntry_DoNotUseDefaultTypeInternal;
extern Response_ArpStatsEntry_DoNotUseDefaultTypeInternal _Response_ArpStatsEntry_DoNotUse_default_instance_;
}  // namespace ns
PROTOBUF_NAMESPACE_OPEN
template<> ::ns::ARPStats* Arena::CreateMaybeMessage<::ns::ARPStats>(Arena*);
template<> ::ns::Request* Arena::CreateMaybeMessage<::ns::Request>(Arena*);
template<> ::ns::Response* Arena::CreateMaybeMessage<::ns::Response>(Arena*);
template<> ::ns::Response_ArpStatsEntry_DoNotUse* Arena::CreateMaybeMessage<::ns::Response_ArpStatsEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ns {

// ===================================================================

class Request final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:ns.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  explicit constexpr Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Request& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Request& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ns.Request";
  }
  protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ns.Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ns_2eproto;
};
// -------------------------------------------------------------------

class Response_ArpStatsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Response_ArpStatsEntry_DoNotUse, 
    std::string, ::ns::ARPStats,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Response_ArpStatsEntry_DoNotUse, 
    std::string, ::ns::ARPStats,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  Response_ArpStatsEntry_DoNotUse();
  explicit constexpr Response_ArpStatsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit Response_ArpStatsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Response_ArpStatsEntry_DoNotUse& other);
  static const Response_ArpStatsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Response_ArpStatsEntry_DoNotUse*>(&_Response_ArpStatsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "ns.Response.ArpStatsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
};

// -------------------------------------------------------------------

class Response final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ns.Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  ~Response() override;
  explicit constexpr Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Response& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ns.Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kArpStatsFieldNumber = 7,
    kPciIdFieldNumber = 1,
    kNumArpFieldNumber = 2,
    kNumBcastArpFieldNumber = 3,
    kNumIpv4FieldNumber = 4,
    kNumIpv6FieldNumber = 5,
    kNumMulticastFieldNumber = 6,
  };
  // map<string, .ns.ARPStats> arp_stats = 7;
  int arp_stats_size() const;
  private:
  int _internal_arp_stats_size() const;
  public:
  void clear_arp_stats();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ns::ARPStats >&
      _internal_arp_stats() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ns::ARPStats >*
      _internal_mutable_arp_stats();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ns::ARPStats >&
      arp_stats() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ns::ARPStats >*
      mutable_arp_stats();

  // string pci_id = 1;
  void clear_pci_id();
  const std::string& pci_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pci_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pci_id();
  PROTOBUF_NODISCARD std::string* release_pci_id();
  void set_allocated_pci_id(std::string* pci_id);
  private:
  const std::string& _internal_pci_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pci_id(const std::string& value);
  std::string* _internal_mutable_pci_id();
  public:

  // uint32 num_arp = 2;
  void clear_num_arp();
  uint32_t num_arp() const;
  void set_num_arp(uint32_t value);
  private:
  uint32_t _internal_num_arp() const;
  void _internal_set_num_arp(uint32_t value);
  public:

  // uint32 num_bcast_arp = 3;
  void clear_num_bcast_arp();
  uint32_t num_bcast_arp() const;
  void set_num_bcast_arp(uint32_t value);
  private:
  uint32_t _internal_num_bcast_arp() const;
  void _internal_set_num_bcast_arp(uint32_t value);
  public:

  // uint32 num_ipv4 = 4;
  void clear_num_ipv4();
  uint32_t num_ipv4() const;
  void set_num_ipv4(uint32_t value);
  private:
  uint32_t _internal_num_ipv4() const;
  void _internal_set_num_ipv4(uint32_t value);
  public:

  // uint32 num_ipv6 = 5;
  void clear_num_ipv6();
  uint32_t num_ipv6() const;
  void set_num_ipv6(uint32_t value);
  private:
  uint32_t _internal_num_ipv6() const;
  void _internal_set_num_ipv6(uint32_t value);
  public:

  // uint32 num_multicast = 6;
  void clear_num_multicast();
  uint32_t num_multicast() const;
  void set_num_multicast(uint32_t value);
  private:
  uint32_t _internal_num_multicast() const;
  void _internal_set_num_multicast(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ns.Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      Response_ArpStatsEntry_DoNotUse,
      std::string, ::ns::ARPStats,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> arp_stats_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pci_id_;
  uint32_t num_arp_;
  uint32_t num_bcast_arp_;
  uint32_t num_ipv4_;
  uint32_t num_ipv6_;
  uint32_t num_multicast_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ns_2eproto;
};
// -------------------------------------------------------------------

class ARPStats final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ns.ARPStats) */ {
 public:
  inline ARPStats() : ARPStats(nullptr) {}
  ~ARPStats() override;
  explicit constexpr ARPStats(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ARPStats(const ARPStats& from);
  ARPStats(ARPStats&& from) noexcept
    : ARPStats() {
    *this = ::std::move(from);
  }

  inline ARPStats& operator=(const ARPStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline ARPStats& operator=(ARPStats&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ARPStats& default_instance() {
    return *internal_default_instance();
  }
  static inline const ARPStats* internal_default_instance() {
    return reinterpret_cast<const ARPStats*>(
               &_ARPStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ARPStats& a, ARPStats& b) {
    a.Swap(&b);
  }
  inline void Swap(ARPStats* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ARPStats* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ARPStats* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ARPStats>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ARPStats& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ARPStats& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ARPStats* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ns.ARPStats";
  }
  protected:
  explicit ARPStats(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNumPktsFieldNumber = 1,
    kRateFieldNumber = 2,
  };
  // uint32 num_pkts = 1;
  void clear_num_pkts();
  uint32_t num_pkts() const;
  void set_num_pkts(uint32_t value);
  private:
  uint32_t _internal_num_pkts() const;
  void _internal_set_num_pkts(uint32_t value);
  public:

  // uint32 rate = 2;
  void clear_rate();
  uint32_t rate() const;
  void set_rate(uint32_t value);
  private:
  uint32_t _internal_rate() const;
  void _internal_set_rate(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ns.ARPStats)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t num_pkts_;
  uint32_t rate_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ns_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Response

// string pci_id = 1;
inline void Response::clear_pci_id() {
  pci_id_.ClearToEmpty();
}
inline const std::string& Response::pci_id() const {
  // @@protoc_insertion_point(field_get:ns.Response.pci_id)
  return _internal_pci_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Response::set_pci_id(ArgT0&& arg0, ArgT... args) {
 
 pci_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ns.Response.pci_id)
}
inline std::string* Response::mutable_pci_id() {
  std::string* _s = _internal_mutable_pci_id();
  // @@protoc_insertion_point(field_mutable:ns.Response.pci_id)
  return _s;
}
inline const std::string& Response::_internal_pci_id() const {
  return pci_id_.Get();
}
inline void Response::_internal_set_pci_id(const std::string& value) {
  
  pci_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Response::_internal_mutable_pci_id() {
  
  return pci_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Response::release_pci_id() {
  // @@protoc_insertion_point(field_release:ns.Response.pci_id)
  return pci_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Response::set_allocated_pci_id(std::string* pci_id) {
  if (pci_id != nullptr) {
    
  } else {
    
  }
  pci_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pci_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (pci_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    pci_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ns.Response.pci_id)
}

// uint32 num_arp = 2;
inline void Response::clear_num_arp() {
  num_arp_ = 0u;
}
inline uint32_t Response::_internal_num_arp() const {
  return num_arp_;
}
inline uint32_t Response::num_arp() const {
  // @@protoc_insertion_point(field_get:ns.Response.num_arp)
  return _internal_num_arp();
}
inline void Response::_internal_set_num_arp(uint32_t value) {
  
  num_arp_ = value;
}
inline void Response::set_num_arp(uint32_t value) {
  _internal_set_num_arp(value);
  // @@protoc_insertion_point(field_set:ns.Response.num_arp)
}

// uint32 num_bcast_arp = 3;
inline void Response::clear_num_bcast_arp() {
  num_bcast_arp_ = 0u;
}
inline uint32_t Response::_internal_num_bcast_arp() const {
  return num_bcast_arp_;
}
inline uint32_t Response::num_bcast_arp() const {
  // @@protoc_insertion_point(field_get:ns.Response.num_bcast_arp)
  return _internal_num_bcast_arp();
}
inline void Response::_internal_set_num_bcast_arp(uint32_t value) {
  
  num_bcast_arp_ = value;
}
inline void Response::set_num_bcast_arp(uint32_t value) {
  _internal_set_num_bcast_arp(value);
  // @@protoc_insertion_point(field_set:ns.Response.num_bcast_arp)
}

// uint32 num_ipv4 = 4;
inline void Response::clear_num_ipv4() {
  num_ipv4_ = 0u;
}
inline uint32_t Response::_internal_num_ipv4() const {
  return num_ipv4_;
}
inline uint32_t Response::num_ipv4() const {
  // @@protoc_insertion_point(field_get:ns.Response.num_ipv4)
  return _internal_num_ipv4();
}
inline void Response::_internal_set_num_ipv4(uint32_t value) {
  
  num_ipv4_ = value;
}
inline void Response::set_num_ipv4(uint32_t value) {
  _internal_set_num_ipv4(value);
  // @@protoc_insertion_point(field_set:ns.Response.num_ipv4)
}

// uint32 num_ipv6 = 5;
inline void Response::clear_num_ipv6() {
  num_ipv6_ = 0u;
}
inline uint32_t Response::_internal_num_ipv6() const {
  return num_ipv6_;
}
inline uint32_t Response::num_ipv6() const {
  // @@protoc_insertion_point(field_get:ns.Response.num_ipv6)
  return _internal_num_ipv6();
}
inline void Response::_internal_set_num_ipv6(uint32_t value) {
  
  num_ipv6_ = value;
}
inline void Response::set_num_ipv6(uint32_t value) {
  _internal_set_num_ipv6(value);
  // @@protoc_insertion_point(field_set:ns.Response.num_ipv6)
}

// uint32 num_multicast = 6;
inline void Response::clear_num_multicast() {
  num_multicast_ = 0u;
}
inline uint32_t Response::_internal_num_multicast() const {
  return num_multicast_;
}
inline uint32_t Response::num_multicast() const {
  // @@protoc_insertion_point(field_get:ns.Response.num_multicast)
  return _internal_num_multicast();
}
inline void Response::_internal_set_num_multicast(uint32_t value) {
  
  num_multicast_ = value;
}
inline void Response::set_num_multicast(uint32_t value) {
  _internal_set_num_multicast(value);
  // @@protoc_insertion_point(field_set:ns.Response.num_multicast)
}

// map<string, .ns.ARPStats> arp_stats = 7;
inline int Response::_internal_arp_stats_size() const {
  return arp_stats_.size();
}
inline int Response::arp_stats_size() const {
  return _internal_arp_stats_size();
}
inline void Response::clear_arp_stats() {
  arp_stats_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ns::ARPStats >&
Response::_internal_arp_stats() const {
  return arp_stats_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ns::ARPStats >&
Response::arp_stats() const {
  // @@protoc_insertion_point(field_map:ns.Response.arp_stats)
  return _internal_arp_stats();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ns::ARPStats >*
Response::_internal_mutable_arp_stats() {
  return arp_stats_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::ns::ARPStats >*
Response::mutable_arp_stats() {
  // @@protoc_insertion_point(field_mutable_map:ns.Response.arp_stats)
  return _internal_mutable_arp_stats();
}

// -------------------------------------------------------------------

// ARPStats

// uint32 num_pkts = 1;
inline void ARPStats::clear_num_pkts() {
  num_pkts_ = 0u;
}
inline uint32_t ARPStats::_internal_num_pkts() const {
  return num_pkts_;
}
inline uint32_t ARPStats::num_pkts() const {
  // @@protoc_insertion_point(field_get:ns.ARPStats.num_pkts)
  return _internal_num_pkts();
}
inline void ARPStats::_internal_set_num_pkts(uint32_t value) {
  
  num_pkts_ = value;
}
inline void ARPStats::set_num_pkts(uint32_t value) {
  _internal_set_num_pkts(value);
  // @@protoc_insertion_point(field_set:ns.ARPStats.num_pkts)
}

// uint32 rate = 2;
inline void ARPStats::clear_rate() {
  rate_ = 0u;
}
inline uint32_t ARPStats::_internal_rate() const {
  return rate_;
}
inline uint32_t ARPStats::rate() const {
  // @@protoc_insertion_point(field_get:ns.ARPStats.rate)
  return _internal_rate();
}
inline void ARPStats::_internal_set_rate(uint32_t value) {
  
  rate_ = value;
}
inline void ARPStats::set_rate(uint32_t value) {
  _internal_set_rate(value);
  // @@protoc_insertion_point(field_set:ns.ARPStats.rate)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ns

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ns_2eproto
